repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-added-large-files
        args: ['--maxkb=250']
      # - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: fix-encoding-pragma
      - id: trailing-whitespace

  -   repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format